massalabs/massa-web3

package.json
We usually publish package with Massa as author and developers as contributors.
=> Fix author and contributors

README.md, examples/smartContracts/contracts/deployer_code.ts, examples/smartContracts/contracts/sc_code.ts, examples/smartContracts/deployer.ts, examples/smartContracts/index.ts, src/index.ts, src/interfaces/IAddressInfo.ts, src/interfaces/ICallData.ts, src/interfaces/IContractData.ts, src/interfaces/IContractStorageData.ts, src/interfaces/IDatastoreEntryInput.ts, src/interfaces/IPublicApiClient.ts, src/interfaces/IReadData.ts, src/interfaces/ISmartContractsClient.ts, src/interfaces/OperationTypes.ts, src/utils/arguments.ts, src/web3/BaseClient.ts, src/web3/PublicApiClient.ts, src/web3/SmartContractsClient.ts
=> use bytearray instead of strings in abi call and storage and remove fee.

README.md
This MR fixes the comment made in here: https://github.com/massalabs/massa-web3/issues/76
=> fixed readme parameters ordering

src/utils/arguments.ts, src/utils/serializers/arrays.ts, test/arguments.spec.ts
Added typed arrays serialization and deserialization.
Original issue for dusa: [issue](https://github.com/massalabs/massa-web3/issues/127)
=> added typed arrays ser & deser

README.md, package-lock.json, package.json, src/web3/Client.ts, src/web3/ClientFactory.ts
This reverts commit c16ddf014013070ad989bfe641e182da5620defa, reversing changes made to f64e830834ff92c21c3ccb964884568060aef546.
=> Revert "Merge pull request #131 from massalabs/feature/wallet-integration"

src/interfaces/IPrivateApiClient.ts
=> docs(interfaces): added documentation for Private Api Client interface

src/utils/arguments.ts, test/arguments.spec.ts
=> docs(utils): Improved arguments documentation

src/web3/ClientFactory.ts
=> 152 update client factory.ts documentation

src/utils/encode_decode_int/index.ts
=> 177 document or improve utils/encode decode int/index.ts 

src/utils/converters.ts
=> improved converters.ts doc

src/utils/serializers/index.ts, src/utils/serializers/numbers.ts
=> 172 index doc

.prettierignore, CONTRIBUTING.md
=> add contributing

src/interfaces/IBlockInfo.ts
=> remove the useless is_in_blockclique from IBlockInfo.ts

src/interfaces/IProvider.ts, src/interfaces/IPublicApiClient.ts, src/interfaces/IReadData.ts, src/interfaces/IReadOperationResult.ts, src/interfaces/IRollsData.ts, src/interfaces/ISerializable.ts, src/interfaces/ISignature.ts, src/interfaces/ISignedMessage.ts, src/interfaces/ISlot.ts, src/interfaces/ISmartContractsClient.ts, src/interfaces/IStakingAddresses.ts, src/interfaces/ISubscribeNewBlocksMessage.ts, src/interfaces/ISubscribedFullBlocksMessage.ts, src/interfaces/ITransactionData.ts, src/interfaces/IWalletClient.ts, src/interfaces/JsonRpcMethods.ts, src/interfaces/JsonRpcResponseData.ts, src/interfaces/OperationTypes.ts, src/utils/Xbqcrypto.ts, src/utils/encode_decode_int/index.ts, src/utils/retryExecuteFunction.ts, src/utils/serializers/arrays.ts, src/utils/time.ts, src/web3/Client.ts, src/web3/PrivateApiClient.ts, tsdoc.json
=> 156 check and update if necessary the interfaces documentation i private api client (included)   ws rpc methods (included) 

.eslintrc.cjs, .prettierignore, examples/smartContracts/contracts/deployer_code.ts, examples/smartContracts/contracts/sc_code.ts, examples/smartContracts/deployer.ts, src/utils/time.ts, src/web3/WalletClient.ts
adding warnings no-unused-vars to eslint config
closes #208
=> update eslint config

package.json, test/arguments.spec.ts
=> add some tests

examples/smartContracts/deployer.ts, src/utils/Xbqcrypto.ts, src/utils/arguments.ts, src/utils/retryExecuteFunction.ts, src/utils/serializers/arrays.ts, src/web3/BaseClient.ts
=> 230 remove typescript any

package-lock.json, package.json
Tested with project / framework examples, no breaking changes detected
closes #235
=> removing esmify

src/web3/BaseClient.ts, src/web3/SmartContractsClient.ts, src/web3/WalletClient.ts
=> 243 testnet 23 objects format changes

.github/workflows/gen-deploy-docs.yml
=> remove env variables

.github/workflows/powered-by.yml
=> fix powered-by.yml

src/interfaces/IReadData.ts
closes #252 
@AurelienFT Can we remove the "fee" ? I can't find any method in web3 that's using it.
=> remove fee from IReadData

.github/workflows/deploy-test-smartContract.yml, .github/workflows/test-wallet-example.yml, README.md, package-lock.json, package.json, src/index.ts, src/utils/serializers/strings.ts
=> adding EventEmitter polyfill

README.md, src/web3/WalletClient.ts, test/web3/walletClient.spec.ts
testing getBaseAccount and setBaseAccount
=> 269 test getBaseAccount, getWalletAccounts

src/interfaces/IProtoFile.ts, src/web3/SmartContractsClient.ts
closes #264 
closes https://github.com/massalabs/massa-sc-toolkit/issues/208 too
=> add the "getProtoFiles" method to the SmartContractsClient class

src/interfaces/IContractReadOperationResponse.ts, src/web3/SmartContractsClient.ts
=> update readSmartContract documentation

README.md, src/index.ts, src/utils/arguments.ts, src/utils/serializers/arrays.ts
and quite some refactoring...
I kept the string array encoding on fixed 100 bytes but i think it should be changed asap...
=> add support for u128 and u256 arrays

README.md, src/web3/SmartContractsClient.ts, test/web3/smartContractsClient.spec.ts
=> tests smartContractsClient: awaitRequiredOperationStatus

README.md, test/utils/time.spec.ts
=> unit tests for time.ts

README.md, test/utils/encode_decode.spec.ts
=> encode_decode unit tests

test/utils/retryExecuteFunction.spec.ts
=> 302 unit tests retry execute function

README.md, src/interfaces/IClient.ts, src/web3/ClientFactory.ts
* add buildnet in defaultProvider
* add new providers
---------
=> add buildnet in defaultProvider (#372)

src/utils/uint8ArrayToString.ts, src/web3/SmartContractsClient.ts
=> fix smells and set getProtoFiles to static

src/index.ts, src/web3/SmartContractsClient.ts
=> export PROTO_FILE_SEPARATOR and MASSA_PROTOFILE_KEY

src/utils/keyAndAddresses.ts, src/web3/WalletClient.ts, test/utils/keyAndAddresses.spec.ts, test/web3/mockData.ts
=> add keyAndAddresses test

src/web3/SmartContractsClient.ts
uint8array was not instanciated. thus the returned value was an array of numbers...
=> fix rpc uint8array buffer instanciation

src/web3/PublicApiClient.ts
=> update getBlocks documentation

README.md
=> update url of readme

src/index.ts, src/utils/index.ts, typedoc.json
closes #420 
added sidebar links, added navigation link redirecting to main doc
=> 420 reorganizing typescript doc

src/web3/SmartContractsClient.ts, test/web3/smartContractsClient.spec.ts
=> use getContractBalance instead

package-lock.json, package.json, src/web3/BaseClient.ts, test/web3/baseClient.spec.ts
This reverts commit 4a6b2c6ed24c350d730cbfebc053b85352c17b04.
=> Revert "update to latest version of axios (#446)"

src/interfaces/ICallData.ts, src/web3/SmartContractsClient.ts, test/web3/mockData.ts, test/web3/smartContractsClient.spec.ts
=> 444 make coins field optional

package.json, src/index.ts, src/utils/bytes.ts, src/utils/keyAndAddresses.ts, src/web3/WalletClient.ts, src/web3/accounts/Web3Account.ts, test/utils/keyAndAddresses.spec.ts, test/web3/mockData.ts
Fix address validation with the right version decoding
=> Fix address validation (#466)

package-lock.json, packages/massa-web3/package.json
Fix this error:
```
✘ [ERROR] No matching export in "node_modules/@massalabs/massa-web3/node_modules/@massalabs/web3-utils/dist/esm/index.js" for import "MASSA_SCALING_FACTOR"
node_modules/@massalabs/massa-web3/dist/esm/web3/SmartContractsClient.js:13:45:
13 │ import { Args, fromMAS, MAX_GAS_CALL, toMAS, MASSA_SCALING_FACTOR, } from '@massalabs/web3-utils';
╵                                              ~~~~~~~~~~~~~~~~~~~~
```
=> update web3 utils in massa-web3

packages/massa-web3/src/web3/SmartContractsClient.ts, packages/massa-web3/test/web3/smartContractsClient.spec.ts
This reverts commit 8511026ca9118c21f85ab916a0afebe56bacc8d5.
=> Revert "Add fee by default for readonly (#551)"

packages/massa-web3/src/experimental/index.ts, packages/massa-web3/src/index.ts
For now, I propose that we export everything to use it and we will fine tune in the future.
=> Add export for all new structures

.github/workflows/workspace-integration-tests.yml, package-lock.json, packages/massa-web3/package.json, packages/massa-web3/src/account.ts, packages/massa-web3/src/basicElements/args.ts
- Add loadash dependency used in the project
- Fix tests
- add method to get AccountOperation in Account
- Add address specific methods in new args
=> Fix tests and improve usability next version

src/contracts-wrappers/mns.ts, test/integration/mns.spec.ts
=> feat: add mns methods
